# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatrans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliasregistration',
            name='credit_card_country',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='aliasregistration',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aliasregistration',
            name='expiry_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aliasregistration',
            name='expiry_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aliasregistration',
            name='request_type',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='charge',
            name='credit_card_country',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='charge',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='expiry_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='expiry_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='request_type',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='credit_card_country',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='request_type',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
