# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatrans', '0002_stricter_expiry_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliasregistration',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
