# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatrans', '0002_auto_20170928_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliasregistration',
            name='credit_card_country',
            field=models.CharField(blank=True, db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='aliasregistration',
            name='payment_method',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='charge',
            name='credit_card_country',
            field=models.CharField(blank=True, db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='credit_card_country',
            field=models.CharField(blank=True, db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, db_index=True, max_length=3),
        ),
    ]
