# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatrans', '0004_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charge',
        ),
        migrations.AddField(
            model_name='payment',
            name='card_alias',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='aliasregistration',
            name='card_alias',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
