# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 08:23
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datatrans', '0006_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliasregistration',
            name='value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='CHF', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='CHF', max_digits=12),
        ),
        migrations.AlterField(
            model_name='refund',
            name='value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='CHF', max_digits=12),
        ),
    ]
